# site settings

title: Simon Weis
description: Software Development
taglong: Software Development
tagshort: Software Development
url: https://simon.w3is.de
baseurl: ""
permalink: pretty
repo: https://github.com/detached/simon.w3is.de

# author settings

author:
  name: Simon Weis
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: detached
  linkedin: simon-weis-920a65230
  mastodon: "@detached"

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
